name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build EXE
        run: |
          mkdir dist
          bun build src/index.ts --compile --outfile dist/antrian

      - name: Copy .env.example
        run: Copy-Item .env.example dist/

      - name: Archive files
        run: Compress-Archive -Path dist/* -DestinationPath antrian-${{ github.ref_name }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: antrian-${{ github.ref_name }}.zip